config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :styleguide, only: :show
  resource :dashboards, only: :show
  resource :conditions, only: :show
  resource :earnings, only: :show
  resource :rates, only: :show
  resource :sales, only: :show


  resources :drivers, only: :create

  namespace :admins do
    resources :drivers
  end

  root 'dashboards#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attach.rb
class Attach < ApplicationRecord
  belongs_to :document

  has_attached_file :file
  do_not_validate_attachment_file_type :file
end

app/models/document.rb
class Document < ApplicationRecord
  KINDS = ['license_front', 'license_back', 'tech_front', 'tech_back', 'osago']

  belongs_to :driver
  has_one    :attach, dependent: :destroy, inverse_of: :document

  validates :kind, inclusion: { in: KINDS }

  accepts_nested_attributes_for :attach, allow_destroy: true

  def file
    (attach || build_attach).file
  end

  def file= file
    attach = (attach || build_attach).assign_attributes(file: file)
  end
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_many :documents, dependent: :destroy

  has_one :driver_license_front, ->{where(documents: { kind: 'license_front' })}, class_name: 'Document', inverse_of: :driver
  has_one :driver_license_back, ->{where(documents: { kind: 'license_back' })}, class_name: 'Document', inverse_of: :driver
  has_one :driver_tech_front, ->{where(documents: { kind: 'tech_front' })}, class_name: 'Document', inverse_of: :driver
  has_one :driver_tech_back, ->{where(documents: { kind: 'tech_back' })}, class_name: 'Document', inverse_of: :driver
  has_one :driver_osago, ->{where(documents: { kind: 'osago' })}, class_name: 'Document', inverse_of: :driver

  accepts_nested_attributes_for :driver_license_front, allow_destroy: true
  accepts_nested_attributes_for :driver_license_back, allow_destroy: true
  accepts_nested_attributes_for :driver_tech_front, allow_destroy: true
  accepts_nested_attributes_for :driver_tech_back, allow_destroy: true
  accepts_nested_attributes_for :driver_osago, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  ROLES = ['admin', 'user']
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  ROLES.each do |role|
    define_method "#{role}?" do
      role == self.role
    end
  end
end

app/controllers/admins/base_controller.rb
class Admins::BaseController < ActionController::Base
  before_action :authenticate_user!
  before_action :check_admin_role

  private
  def check_admin_role
    unless current_user.admin?
      raise ActionController::RoutingError.new('permission denied')
    end
  end
end

app/controllers/admins/drivers_controller.rb
class Admins::DriversController < Admins::BaseController
  def create
    update_driver new_driver
  end

  def update
    update_driver driver
  end

  private
  def update_driver driver
    if driver.update_attributes(driver_params)
      redirect_to admins_drivers_url
    else
      render(driver.persisted? ? :edit : :new)
    end
  end

  helper_method :drivers
  def drivers
    @drivers ||= Driver.all
  end

  helper_method :driver
  def driver
    @driver ||= drivers.find params[:id]
  end

  helper_method :new_driver
  def new_driver
    @new_driver ||= Driver.new(
      driver_license_front: Document.new(kind: :license_front),
      driver_license_back: Document.new(kind: :license_back),
      driver_tech_front: Document.new(kind: :tech_front),
      driver_tech_back: Document.new(kind: :tech_back),
      driver_osago: Document.new(kind: :osago)
    )
  end

  def driver_params
    params.require(:driver).permit(
      :first_name, :last_name, :phone, :email, :bank, :city,
      driver_license_front_attributes: [:id, :file],
      driver_license_back_attributes: [:id, :file],
      driver_tech_front_attributes: [:id, :file],
      driver_tech_back_attributes: [:id, :file],
      driver_osago_attributes: [:id, :file]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/conditions_controller.rb
class ConditionsController < ActionController::Base
  layout 'layouts/application'

  def show
    # put any code here that you need
    # (although for a static view you probably won't have any)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ActionController::Base
  layout 'layouts/application'

  def show
    # put any code here that you need
    # (although for a static view you probably won't have any)
  end

  helper_method :new_driver
  def new_driver
    @new_driver ||= Driver.new(
      driver_license_front: Document.new(kind: :license_front),
      driver_license_back: Document.new(kind: :license_back),
      driver_tech_front: Document.new(kind: :tech_front),
      driver_tech_back: Document.new(kind: :tech_back),
      driver_osago: Document.new(kind: :osago)
    )
  end
end

app/controllers/drivers_controller.rb
class DriversController < ActionController::Base
  def index
    @drivers = Driver.all
  end

  def create
    @driver = Driver.new()
    if @driver.update_attributes(driver_params)
      # success
    else
      # error
    end
  end

  private

  def driver_params
    params.require(:driver).permit(:last_name,
                                   :first_name,
                                   :phone,
                                   :email,
                                   :bank,
                                   :city,
                                   driver_license_front_attributes: [:id, :file],
                                   driver_license_back_attributes: [:id, :file],
                                   driver_tech_front_attributes: [:id, :file],
                                   driver_tech_back_attributes: [:id, :file],
                                   driver_osago_attributes: [:id, :file])
  end
end

app/controllers/earnings_controller.rb
class EarningsController < ActionController::Base
  layout 'layouts/application'

  def show
    # put any code here that you need
    # (although for a static view you probably won't have any)
  end
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  def help
    # put any code here that you need
    # (although for a static view you probably won't have any)
  end
end

app/controllers/rates_controller.rb
class RatesController < ActionController::Base
  layout 'layouts/application'

  def show
    # put any code here that you need
    # (although for a static view you probably won't have any)
  end
end

app/controllers/sales_controller.rb
class SalesController < ActionController::Base
  layout 'layouts/application'

  def show
    # put any code here that you need
    # (although for a static view you probably won't have any)
  end
end

app/controllers/styleguides_controller.rb
class StyleguidesController < ActionController::Base
  before_action :authenticate_user!

  layout 'styleguide'

  def show
    # put any code here that you need
    # (although for a static view you probably won't have any)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/abouts/show.html.erb
<%= render "shared/header" %>

<div class="container">
  <div class="module module_theme_inner">
    <div class="text text_size_h1 text_transform_uppercase spacer_bottom-40">
      О нас
    </div>
    <div class="text text_size_h3 text_transform_uppercase spacer_bottom-110">
      Преимущества работы С UberGo
    </div>
  </div>

  <div class="text text_size_h2 spacer_bottom-25">
    Мы – профессионалы!
  </div>

  <ul class="list">
    <li class="list__item text spacer_bottom-25">
      Подключаем водителей в считанные часы с минимальным пакетом документов (права, тех. паспорт, страховка). Вам не надо открывать ФОП или ТОВ.
    </li>
    <li class="list__item text spacer_bottom-25">
      Работайте, когда Вам это удобно, даже после основной работы.
    </li>
    <li class="list__item text spacer_bottom-25">
      У Вас полная свобода действий и никаких начальников!
    </li>
    <li class="list__item text spacer_bottom-25">
      Мы стремимся оказать лучший сервис для наших клиентов!  МЕГА-СКИДКИ до 50% на топливо, страховки, кофе и многое другое!
    </li>
  </ul>
</div>

app/views/admins/drivers/_document_appearing.html.erb
<h3>Image for <%= doc.kind.to_s.humanize %></h3>
<%= image_tag doc.file.url, style: "max-width: 300px;" %>

app/views/admins/drivers/_document_fields.html.erb
<%= form.fields_for doc_type do |n_form|  %>
  <%= render "document_appearing", doc: n_form.object %>
  <div class="field">
    <%= n_form.label :file %>
    <%= n_form.file_field :file %>
   </div>
<% end %>

app/views/admins/drivers/_form.html.erb
<%= form_with(model: driver, url: [:admins, driver], local: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :driver_last_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :driver_first_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :driver_phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :driver_email %>
  </div>

  <div class="field">
    <%= form.label :bank %>
    <%= form.text_field :bank, id: :driver_bank %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :driver_city %>
  </div>

  <%= render "document_fields", form: form, doc_type: :driver_license_front %>
  <%= render "document_fields", form: form, doc_type: :driver_license_back %>
  <%= render "document_fields", form: form, doc_type: :driver_tech_front %>
  <%= render "document_fields", form: form, doc_type: :driver_tech_back %>
  <%= render "document_fields", form: form, doc_type: :driver_osago %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render "form" %>

<%= link_to "Show", [:admins, driver] %> |
<%= link_to "Back", admins_drivers_path %>

app/views/admins/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Bank</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% drivers.each do |driver| %>
      <tr>
        <td><%= driver.first_name %></td>
        <td><%= driver.last_name %></td>
        <td><%= driver.phone %></td>
        <td><%= driver.email %></td>
        <td><%= driver.bank %></td>
        <td><%= driver.city %></td>
        <td><%= link_to "Show", [:admins, driver] %></td>
        <td><%= link_to "Edit", edit_admins_driver_path(driver) %></td>
        <td><%= link_to "Destroy", [:admins, driver], method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Driver", new_admins_driver_path %>

app/views/admins/drivers/new.html.erb
<h1>New Driver</h1>

<%= render "form", driver: new_driver %>

<%= link_to "Back", admins_drivers_path %>

app/views/admins/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= driver.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= driver.first_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= driver.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= driver.email %>
</p>

<p>
  <strong>Bank:</strong>
  <%= driver.bank %>
</p>

<p>
  <strong>City:</strong>
  <%= driver.city %>
</p>

<h2> Document list </h2>

<% driver.documents.each do |doc| %>
  <%= render "document_appearing", doc: doc %>
<% end %>

<%= link_to "Edit", edit_admins_driver_path(driver) %> |
<%= link_to "Back", admins_drivers_path %>

app/views/conditions/show.html.erb
<%= render "shared/header" %>

<div class="container">
  <div class="module module_theme_inner">
    <div class="text text_size_h1 text_transform_uppercase spacer_bottom-40">
      Условия работы
    </div>
  </div>
  <div class="text text_size_h3 text_transform_uppercase spacer_bottom-25">
    Начало работы
  </div>
  <div class="spacer_bottom-25">
    <div class="text">
      1. <a href="https://www.uber.com/signup/drive/">Зарегистрируйтесь онлайн</a>
    </div>
    <div class="text">
      2. <a href="https://www.uber.com/uk-UA/drive/resources/vehicle-requirements/">Технические требования для вашего автомобиля</a>
    </div>
  </div>

  <div class="text text_size_h3 text_transform_uppercase spacer_bottom-25">
    Чем еще мы можем помочь?
  </div>
  <div class="text">
    <a href="https://help.uber.com/partners">Поддержка</a>
  </div>
  <div class="text">
    Помочь настроить и активироваь Ваш аккаунт, начать работать с приложением, настроить тарифы
  </div>
  <div class="text">
    <a href="https://www.uber.com/uk-UA/drive/resources/contact-us/">Связь с Uber</a>
  </div>
  <div class="text">
    Вопросы о регистрации, сотрудничестве,работе с приложением
  </div>
  <div class="text">
    <a href="https://www.uber.com/a/signup/drive/deliver/?70307t=">Зарабатывайте больше</a>
  </div>
  <div class="text">
    Доставка с UBEREATS
  </div>
</div>

<div class="container">
  <div class="module module_theme_inner">
    <div class="row spacer_bottom-75">
      <div class="col-sm-5 offset-sm-1 spacer_bottom-40">
            <h2 class="text text_size_h2 spacer_bottom-25">Uber X</h2>
            <div class="text">
              Опрятная иномарка в исправном техническом состоянии не старше 1995 года. Марка автомобиля, например: Chevrolet Aveo, Chevrolet Lacetty, Skoda Rapid, VW Polo, Hyundai Accent, Opel Astra – или аналогичные марки.
            </div>
      </div>
      <div class="col-sm-5">
            <h2 class="text text_size_h2 spacer_bottom-25">Uber VAN</h2>
            <div class="text">
              Опрятный минивэн или микроавтобус в исправном техническом состоянии для перевозки 6 и более пассажиров.
            </div>
      </div>
    </div>

    <div class="row spacer_bottom-75">

    </div>
  </div>
</div>


<div class="module module_theme_driver">
  <div class="container">
    <div class="text text_size_h1 text_color_white text_transform_uppercase spacer_bottom-40">
      Driver
    </div>
    <div class="row spacer_bottom-25">
      <div class="col-sm-4 offset-sm-4">
        <a href="#" class="button">Подключиться</a>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_driver_document_fields.html.erb
<%= form.fields_for doc_type do |n_form|  %>
  <%= n_form.file_field :file, class: "form-uber__field" %>
<% end %>

app/views/dashboards/_driver_form.html.erb
<%= form_for new_driver, class: "form-uber" do |f| %>
  <div class="form-uber__item">
    <%= f.text_field :last_name, placeholder: "Фамилия", class: "form-uber__field" %>
  </div>
  <div class="form-uber__item">
    <%= f.text_field :first_name, placeholder: "Имя", class: "form-uber__field" %>
  </div>
  <div class="form-uber__item">
    <%= f.telephone_field :phone, placeholder: "Телефон", class: "form-uber__field" %>
  </div>
  <div class="form-uber__item">
    <%= f.email_field :email, placeholder: "Email", class: "form-uber__field" %>
  </div>
  <div class="form-uber__item">
    <%= f.text_field :bank, placeholder: "№ Карты. Название банка", class: "form-uber__field" %>
  </div>
  <div class="form-uber__item">
    <%= f.select :city, options_for_select(["Киев", "Днепр"]), {}, class: "form-uber__field" %>
  </div>
  <div class="form-uber__item">
    <label>Права</label>
    <%= render "driver_document_fields", form: f, doc_type: :driver_license_front %>
  <div class="form-uber__item">
    <label>Права обратная сторона</label>
    <%= render "driver_document_fields", form: f, doc_type: :driver_license_back %>
  </div>
  <div class="form-uber__item">
    <label>Техпаспорт</label>
    <%= render "driver_document_fields", form: f, doc_type: :driver_tech_front %>
  </div>
  <div class="form-uber__item">
    <label>Техпаспорт обратная сторона</label>
    <%= render "driver_document_fields", form: f, doc_type: :driver_tech_back %>
  </div>
  <div class="form-uber__item">
    <label>Страховой полис ОСАГО</label>
    <%= render "driver_document_fields", form: f, doc_type: :driver_osago %>
  </div>
  <div class="form-uber__item">
    <%= f.submit "Отправить" %>
  </div>
<% end %>

app/views/dashboards/show.html.erb
<%= render "shared/header" %>

<div class="module module_theme_greeting">
  <div class="text text_size_h1 text_color_white text_transform_uppercase spacer_bottom-40">
    Стань водителем UBER
  </div>
  <div class="container">
    <div class="text text_size_h3 text_color_white spacer_bottom-110">
      UberGo - официальный представитель компании Uber в Украине.
      <br>
      UberGo дает возможность водителям заработать сегодня.
      <br>
      Свободный график, ежедневные выплаты, бонусы за поездки, скидки на топливо.
      <br>
      Зарабатывайте до 40000 грн/мес на лучших условиях - комиссия 6%
    </div>
    <div class="row d-flex justify-content-center">
      <div class="col-lg-3 pb-4">
        <a href="#" class="button"  data-toggle="modal" data-target=".modal">Стать водителем UBER</a>
      </div>
    </div>
  </div>
</div>

<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content popup">
      <span class="popup__close" data-dismiss="modal">×</span>

      <h2 class="text text_size_h3 spacer_bottom-25">Стать водителем UBER</h2>

      <%= render "driver_form" %>
    </div>
  </div>
</div>

app/views/earnings/show.html.erb
<%= render "shared/header" %>

<div class="container">
  <div class="module module_theme_inner">
    <div class="text text_size_h1 text_transform_uppercase spacer_bottom-40">
      Расчет заработной платы
    </div>
    <div class="text text_size_h3 text_transform_uppercase spacer_bottom-110">
      Все прозрачно!
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UberGo</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700",
      media: "all" %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <div class="position-absolute">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/styleguide.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UberGo</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700",
      media: "all" %>
    <%= stylesheet_link_tag "styleguide", media: "all" %>
    <%= javascript_include_tag "styleguide" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rates/show.html.erb
<%= render "shared/header" %>

<div class="container">
  <div class="module module_theme_inner">
    <div class="text text_size_h1 text_transform_uppercase spacer_bottom-40">
      Тарифы
    </div>
    <div class="text text_size_h3 text_transform_uppercase spacer_bottom-110">
      Информация о наших тарифах
    </div>
  </div>

  <div class="spacer_bottom-110">
    <table class="t431__table">
      <thead class="t431__thead">
        <tr>
          <th class="t431__th">Город, продукт</th>
          <th class="t431__th">Подача автомобиля</th>
          <th class="t431__th">Минимальный тариф</th>
          <th class="t431__th">Стоимость км пути</th>
          <th class="t431__th">Стоимость мин пути</th>
          <th class="t431__th">Отмена заказа</th>
        </tr>
      </thead>
      <tbody class="t431__tbody">
        <tr class="t431__oddrow">
          <td class="t431__td">Киев Uber X</td>
          <td class="t431__td">25</td>
          <td class="t431__td">40</td>
          <td class="t431__td">4.5</td>
          <td class="t431__td">1.15</td>
          <td class="t431__td">40</td>
        </tr>
        <tr class="t431__evenrow">
          <td class="t431__td">Киев Uber Select</td>
          <td class="t431__td">30</td>
          <td class="t431__td">55</td>
          <td class="t431__td">4.6</td>
          <td class="t431__td">1.3</td>
          <td class="t431__td">55</td>
        </tr>
        <tr class="t431__oddrow">
          <td class="t431__td">Киев Uber Black</td>
          <td class="t431__td">85</td>
          <td class="t431__td">200</td>
          <td class="t431__td">10</td>
          <td class="t431__td">4.6</td>
          <td class="t431__td">200</td>
        </tr>
        <tr class="t431__evenrow">
          <td class="t431__td">Киев Uber VAN</td>
          <td class="t431__td">45</td>
          <td class="t431__td">80</td>
          <td class="t431__td">5.8</td>
          <td class="t431__td">1.8</td>
          <td class="t431__td">80</td>
        </tr>
        <tr class="t431__oddrow">
          <td class="t431__td">Одесса Uber X</td>
          <td class="t431__td">20</td>
          <td class="t431__td">35</td>
          <td class="t431__td">4.5</td>
          <td class="t431__td">1.3</td>
          <td class="t431__td">35</td>
        </tr>
        <tr class="t431__evenrow">
          <td class="t431__td">Одесса Uber Select</td>
          <td class="t431__td">30</td>
          <td class="t431__td">55</td>
          <td class="t431__td">4.7</td>
          <td class="t431__td">1.7</td>
          <td class="t431__td">55</td>
        </tr>
        <tr class="t431__oddrow">
          <td class="t431__td">Львов Uber X</td>
          <td class="t431__td">21</td>
          <td class="t431__td">35</td>
          <td class="t431__td">5</td>
          <td class="t431__td">1.2</td>
          <td class="t431__td">35</td>
        </tr>
        <tr class="t431__evenrow">
          <td class="t431__td">Львов Uber Select</td>
          <td class="t431__td">28</td>
          <td class="t431__td">50</td>
          <td class="t431__td">5,3</td>
          <td class="t431__td">1,35</td>
          <td class="t431__td">50</td>
        </tr>
        <tr class="t431__oddrow">
          <td class="t431__td">Днепр Uber X</td>
          <td class="t431__td">23</td>
          <td class="t431__td">35</td>
          <td class="t431__td">4</td>
          <td class="t431__td">1.1</td>
          <td class="t431__td">35</td>
        </tr>
        <tr class="t431__evenrow">
          <td class="t431__td">Днепр Uber Select</td>
          <td class="t431__td">26</td>
          <td class="t431__td">50</td>
          <td class="t431__td">5</td>
          <td class="t431__td">1,35</td>
          <td class="t431__td">50</td>
        </tr>
        <tr class="t431__oddrow">
          <td class="t431__td">Харьков Uber X</td>
          <td class="t431__td">30</td>
          <td class="t431__td">40</td>
          <td class="t431__td">3.5</td>
          <td class="t431__td">0.9</td>
          <td class="t431__td">40</td>
        </tr>
        <tr class="t431__evenrow">
          <td class="t431__td">Харьков Uber Select</td>
          <td class="t431__td">28</td>
          <td class="t431__td">50</td>
          <td class="t431__td">4</td>
          <td class="t431__td">1,2</td>
          <td class="t431__td">50</td>
        </tr>
        <tr class="t431__oddrow">
          <td class="t431__td">Запорожье Uber X</td>
          <td class="t431__td">21</td>
          <td class="t431__td">30</td>
          <td class="t431__td">3.7</td>
          <td class="t431__td">1</td>
          <td class="t431__td">30</td>
        </tr>
        <tr class="t431__evenrow">
          <td class="t431__td">Винница Uber X</td>
          <td class="t431__td">10</td>
          <td class="t431__td">25</td>
          <td class="t431__td">5,2</td>
          <td class="t431__td">1.15</td>
          <td class="t431__td">25</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>